export enum MoveLearnMethodId {
  LEVEL_UP = 1,
  EGG,
  TUTOR,
  MACHINE,
  STADIUM_SURFING_PIKACHU,
  LIGHT_BALL_EGG,
  COLOSSEUM_PURIFICATION,
  XD_SHADOW,
  XD_PURIFICATION,
  FORM_CHANGE,
  ZYGARDE_CUBE,
}
